import { Station } from '../domain/models/station.entity.js';
import { StationTicket, TICKET_STATUS } from '../domain/models/station-ticket.entity.js';

export const MOCK_STATIONS = [
    // ── Sede Central (branch-001) ────────────────────────────────────────
    new Station({ id: 1, name: 'Sucursal 001 Cocina Caliente', description: 'Platos salteados, fritos y a la plancha', color: '#ef4444', isActive: true, sucursalId: 'branch-001' }),
    new Station({ id: 2, name: 'Sucursal 001 Cocina Fría',     description: 'Ceviches, ensaladas y entradas frías',   color: '#10b981', isActive: true, sucursalId: 'branch-001' }),
    new Station({ id: 3, name: 'Sucursal 001 Pastelería',      description: 'Postres, pasteles y repostería',         color: '#ec4899', isActive: true, sucursalId: 'branch-001' }),
    new Station({ id: 4, name: 'Sucursal 001 Bar',             description: 'Bebidas frías, calientes y cócteles',    color: '#8b5cf6', isActive: true, sucursalId: 'branch-001' }),
    new Station({ id: 5, name: 'Sucursal 001 Pastas',          description: 'Pastas, arroces y risottos',             color: '#f59e0b', isActive: true, sucursalId: 'branch-001' }),
    // ── Sucursal Miraflores (branch-002) ─────────────────────────────────
    new Station({ id: 6, name: 'Sucursal 002 Cocina General',  description: 'Cocina principal Miraflores',            color: '#ef4444', isActive: true, sucursalId: 'branch-002' }),
    new Station({ id: 7, name: 'Sucursal 002 Bar',  description: 'Barra de bebidas Miraflores',            color: '#8b5cf6', isActive: true, sucursalId: 'branch-002' }),
];

export const MOCK_TICKETS = [
    // ── Sede Central (branch-001) ────────────────────────────────────────
    new StationTicket({ id: 1, stationId: 1, stationName: 'Cocina Caliente', saleId: 1201, tableNumber: 2, items: [{ menuItemId: 3, menuItemName: 'Lomo Saltado',     quantity: 2, note: '' }, { menuItemId: 4, menuItemName: 'Pollo a la Brasa', quantity: 1, note: 'Bien cocido' }], status: TICKET_STATUS.PREPARING, createdAt: new Date(Date.now() - 43 * 60000), startedAt: new Date(Date.now() - 30 * 60000), sucursalId: 'branch-001' }),
    new StationTicket({ id: 2, stationId: 2, stationName: 'Cocina Fría',     saleId: 1201, tableNumber: 2, items: [{ menuItemId: 1, menuItemName: 'Ceviche Clásico',  quantity: 2, note: '' }],                                                                                             status: TICKET_STATUS.READY,     createdAt: new Date(Date.now() - 43 * 60000), startedAt: new Date(Date.now() - 38 * 60000), readyAt: new Date(Date.now() - 22 * 60000), sucursalId: 'branch-001' }),
    new StationTicket({ id: 3, stationId: 4, stationName: 'Bar',             saleId: 1201, tableNumber: 2, items: [{ menuItemId: 10, menuItemName: 'Limonada de la Casa', quantity: 2, note: 'Sin azúcar' }],                                                                              status: TICKET_STATUS.READY,     createdAt: new Date(Date.now() - 43 * 60000), startedAt: new Date(Date.now() - 42 * 60000), readyAt: new Date(Date.now() - 38 * 60000), sucursalId: 'branch-001' }),
    new StationTicket({ id: 4, stationId: 1, stationName: 'Cocina Caliente', saleId: 1215, tableNumber: 4, items: [{ menuItemId: 3, menuItemName: 'Lomo Saltado',     quantity: 1, note: '' }, { menuItemId: 5, menuItemName: 'Salmón al Limón', quantity: 2, note: '' }],               status: TICKET_STATUS.READY,     createdAt: new Date(Date.now() - 70 * 60000), startedAt: new Date(Date.now() - 65 * 60000), readyAt: new Date(Date.now() - 45 * 60000), sucursalId: 'branch-001' }),
    new StationTicket({ id: 5, stationId: 5, stationName: 'Pastas',          saleId: 1215, tableNumber: 4, items: [{ menuItemId: 6, menuItemName: 'Pasta Alfredo',    quantity: 2, note: '' }, { menuItemId: 7, menuItemName: 'Lasagna Boloñesa', quantity: 1, note: '' }],              status: TICKET_STATUS.PREPARING, createdAt: new Date(Date.now() - 70 * 60000), startedAt: new Date(Date.now() - 50 * 60000), sucursalId: 'branch-001' }),
    new StationTicket({ id: 6, stationId: 1, stationName: 'Cocina Caliente', saleId: 1246, tableNumber: 8, items: [{ menuItemId: 4, menuItemName: 'Pollo a la Brasa', quantity: 2, note: '' }],                                                                                           status: TICKET_STATUS.RECEIVED,  createdAt: new Date(Date.now() -  5 * 60000), sucursalId: 'branch-001' }),
    new StationTicket({ id: 7, stationId: 4, stationName: 'Bar',             saleId: 1246, tableNumber: 8, items: [{ menuItemId: 10, menuItemName: 'Limonada de la Casa', quantity: 3, note: '' }],                                                                                       status: TICKET_STATUS.PREPARING, createdAt: new Date(Date.now() -  5 * 60000), startedAt: new Date(Date.now() -  3 * 60000), sucursalId: 'branch-001' }),
    // ── Sucursal Miraflores (branch-002) ─────────────────────────────────
    new StationTicket({ id: 8, stationId: 6, stationName: 'Cocina General',  saleId: 1300, tableNumber: 2, items: [{ menuItemId: 14, menuItemName: 'Ají de Gallina', quantity: 2, note: '' }], status: TICKET_STATUS.PREPARING, createdAt: new Date(Date.now() - 20 * 60000), startedAt: new Date(Date.now() - 15 * 60000), sucursalId: 'branch-002' }),
    new StationTicket({ id: 9, stationId: 7, stationName: 'Bar Miraflores',  saleId: 1300, tableNumber: 2, items: [{ menuItemId: 15, menuItemName: 'Chicha Morada', quantity: 2, note: '' }], status: TICKET_STATUS.READY,     createdAt: new Date(Date.now() - 20 * 60000), startedAt: new Date(Date.now() - 18 * 60000), readyAt: new Date(Date.now() - 10 * 60000), sucursalId: 'branch-002' }),
];
