import { UserProfile } from '../domain/models/user-profile.entity.js'

/**
 * Mock data para el módulo de usuarios.
 * OWNER (propietario de la empresa) + usuarios operativos asignados a las sucursales mock.
 */
export const MOCK_USERS = [
    new UserProfile({
        id:              'owner-001',
        username:        'admin',
        nombres:         'Alejandro',
        apellidos:       'Navarro Ruiz',
        email:           'admin@gastrosuite.pe',
        telefono:        '999 000 111',
        tipoDocumento:   'DNI',
        numeroDocumento: '10000001',
        role:            'OWNER',
        sucursalId:      null,
        sucursalNombre:  '',
        isActive:        true,
        createdAt:       '2024-01-01',
    }),
    new UserProfile({
        id:              'user-001',
        username:        'carlos.mendoza',
        nombres:         'Carlos',
        apellidos:       'Mendoza Rivera',
        email:           'carlos.mendoza@gastrosuite.pe',
        telefono:        '987 654 321',
        tipoDocumento:   'DNI',
        numeroDocumento: '45678912',
        role:            'BRANCH_ADMIN',
        sucursalId:      'branch-001',
        sucursalNombre:  'Sede Central',
        isActive:        true,
        createdAt:       '2024-02-10',
    }),
    new UserProfile({
        id:              'user-002',
        username:        'maria.garcia',
        nombres:         'María',
        apellidos:       'García López',
        email:           'maria.garcia@gastrosuite.pe',
        telefono:        '912 345 678',
        tipoDocumento:   'DNI',
        numeroDocumento: '78912345',
        role:            'WAITER',
        sucursalId:      'branch-001',
        sucursalNombre:  'Sede Central',
        isActive:        true,
        createdAt:       '2024-03-15',
    }),
    new UserProfile({
        id:              'user-003',
        username:        'jose.torres',
        nombres:         'José',
        apellidos:       'Torres Huamán',
        email:           'jose.torres@gastrosuite.pe',
        telefono:        '956 789 012',
        tipoDocumento:   'DNI',
        numeroDocumento: '12345678',
        role:            'COOK',
        sucursalId:      'branch-001',
        sucursalNombre:  'Sede Central',
        isActive:        true,
        createdAt:       '2024-04-20',
    }),
    new UserProfile({
        id:              'user-004',
        username:        'ana.quispe',
        nombres:         'Ana',
        apellidos:       'Quispe Vargas',
        email:           'ana.quispe@gastrosuite.pe',
        telefono:        '934 567 890',
        tipoDocumento:   'DNI',
        numeroDocumento: '56789123',
        role:            'CASHIER',
        sucursalId:      'branch-001',
        sucursalNombre:  'Sede Central',
        isActive:        true,
        createdAt:       '2024-05-01',
    }),
    new UserProfile({
        id:              'user-005',
        username:        'luis.paredes',
        nombres:         'Luis',
        apellidos:       'Paredes Soto',
        email:           'luis.paredes@gastrosuite.pe',
        telefono:        '978 123 456',
        tipoDocumento:   'CE',
        numeroDocumento: '001234567',
        role:            'BRANCH_ADMIN',
        sucursalId:      'branch-002',
        sucursalNombre:  'Sucursal Miraflores',
        isActive:        true,
        createdAt:       '2024-06-10',
    }),
    new UserProfile({
        id:              'user-006',
        username:        'rosa.flores',
        nombres:         'Rosa',
        apellidos:       'Flores Díaz',
        email:           'rosa.flores@gastrosuite.pe',
        telefono:        '945 678 123',
        tipoDocumento:   'DNI',
        numeroDocumento: '89123456',
        role:            'WAITER',
        sucursalId:      'branch-002',
        sucursalNombre:  'Sucursal Miraflores',
        isActive:        false,
        createdAt:       '2024-07-05',
    }),
]
