import { Product, STOCK_STATUS } from '../domain/models/product.entity.js';
import { InventoryCategory } from '../domain/models/inventory-category.entity.js';
import { StockMovement, MOVEMENT_TYPE, MOVEMENT_DIRECTION } from '../domain/models/stock-movement.entity.js';

export const MOCK_INVENTORY_CATEGORIES = [
    // ── Sede Central (branch-001) ────────────────────────────────────────
    new InventoryCategory({ id: 1, name: 'Aceites y Condimentos', color: '#f59e0b', description: 'Aceites, especias y condimentos para cocina',  sortOrder: 1, sucursalId: 'branch-001' }),
    new InventoryCategory({ id: 2, name: 'Granos y Cereales',     color: '#8b5cf6', description: 'Arroz, pasta, legumbres y cereales',           sortOrder: 2, sucursalId: 'branch-001' }),
    new InventoryCategory({ id: 3, name: 'Carnes y Pescados',     color: '#ef4444', description: 'Carnes rojas, aves y mariscos frescos',        sortOrder: 3, sucursalId: 'branch-001' }),
    new InventoryCategory({ id: 4, name: 'Lácteos',               color: '#3b82f6', description: 'Leche, quesos, cremas y derivados',            sortOrder: 4, sucursalId: 'branch-001' }),
    new InventoryCategory({ id: 5, name: 'Frutas y Verduras',     color: '#22c55e', description: 'Frutas frescas, verduras y hortalizas',        sortOrder: 5, sucursalId: 'branch-001' }),
    new InventoryCategory({ id: 6, name: 'Bebidas e Insumos',     color: '#06b6d4', description: 'Café, té, bebidas y otros insumos',            sortOrder: 6, sucursalId: 'branch-001' }),
    new InventoryCategory({ id: 7, name: 'Descartables',          color: '#6b7280', description: 'Servilletas, envases y productos desechables', sortOrder: 7, sucursalId: 'branch-001' }),
    // ── Sucursal Miraflores (branch-002) ─────────────────────────────────
    new InventoryCategory({ id: 8,  name: 'Aceites y Condimentos', color: '#f59e0b', description: 'Aceites y condimentos', sortOrder: 1, sucursalId: 'branch-002' }),
    new InventoryCategory({ id: 9,  name: 'Carnes y Pescados',     color: '#ef4444', description: 'Carnes y mariscos',     sortOrder: 2, sucursalId: 'branch-002' }),
    new InventoryCategory({ id: 10, name: 'Frutas y Verduras',     color: '#22c55e', description: 'Frutas y verduras',     sortOrder: 3, sucursalId: 'branch-002' }),
];

export const MOCK_PRODUCTS = [
    // ── Sede Central (branch-001) ────────────────────────────────────────
    new Product({ id: 1,  name: 'Aceite de Oliva Extra Virgen', description: 'Aceite importado para cocina y ensaladas',     sku: 'INV-ACE-001', price: 45.00, cost: 32.00, stock: 24,  minStock: 5,  maxStock: 50,  unit: 'botella',  categoryId: 1, category: 'Aceites y Condimentos', isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 2,  name: 'Arroz Extra Graneado',         description: 'Arroz de grano largo para guarniciones',        sku: 'INV-ARR-001', price: 4.50,  cost: 3.00,  stock: 80,  minStock: 20, maxStock: 200, unit: 'kg',       categoryId: 2, category: 'Granos y Cereales',      isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 3,  name: 'Filete de Salmón',             description: 'Salmón fresco del Atlántico 200g',              sku: 'INV-SAL-001', price: 38.00, cost: 28.00, stock: 12,  minStock: 5,  maxStock: 30,  unit: 'unidad',   categoryId: 3, category: 'Carnes y Pescados',      isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 4,  name: 'Pechuga de Pollo',             description: 'Pechuga deshuesada por kilo',                   sku: 'INV-POL-001', price: 18.00, cost: 12.00, stock: 3,   minStock: 10, maxStock: 50,  unit: 'kg',       categoryId: 3, category: 'Carnes y Pescados',      isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 5,  name: 'Queso Parmesano',              description: 'Queso parmesano importado para pastas',          sku: 'INV-QUE-001', price: 55.00, cost: 40.00, stock: 8,   minStock: 3,  maxStock: 20,  unit: 'unidad',   categoryId: 4, category: 'Lácteos',                isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 6,  name: 'Crema de Leche',               description: 'Crema fresca para salsas y postres',            sku: 'INV-CRE-001', price: 8.50,  cost: 5.50,  stock: 15,  minStock: 5,  maxStock: 40,  unit: 'litro',    categoryId: 4, category: 'Lácteos',                isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 7,  name: 'Fettuccine Pasta',             description: 'Pasta seca italiana 500g',                      sku: 'INV-PAS-001', price: 12.00, cost: 7.00,  stock: 30,  minStock: 10, maxStock: 100, unit: 'paquete',  categoryId: 2, category: 'Granos y Cereales',      isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 8,  name: 'Limones Frescos',              description: 'Limones para ceviche y bebidas',                sku: 'INV-LIM-001', price: 3.00,  cost: 1.50,  stock: 0,   minStock: 20, maxStock: 100, unit: 'kg',       categoryId: 5, category: 'Frutas y Verduras',      isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 9,  name: 'Cebolla Roja',                 description: 'Cebolla roja para ceviche y ensaladas',         sku: 'INV-CEB-001', price: 2.50,  cost: 1.20,  stock: 45,  minStock: 15, maxStock: 80,  unit: 'kg',       categoryId: 5, category: 'Frutas y Verduras',      isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 10, name: 'Café Molido Premium',           description: 'Café arábica molido para espresso',             sku: 'INV-CAF-001', price: 35.00, cost: 22.00, stock: 10,  minStock: 3,  maxStock: 25,  unit: 'bolsa',    categoryId: 6, category: 'Bebidas e Insumos',      isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 11, name: 'Servilletas Decoradas',         description: 'Paquete x100 servilletas de papel',             sku: 'INV-SER-001', price: 8.00,  cost: 4.50,  stock: 50,  minStock: 10, maxStock: 200, unit: 'paquete',  categoryId: 7, category: 'Descartables',            isActive: true, sucursalId: 'branch-001' }),
    new Product({ id: 12, name: 'Ají Amarillo en Pasta',        description: 'Pasta de ají amarillo para platos peruanos',    sku: 'INV-AJI-001', price: 6.00,  cost: 3.50,  stock: 18,  minStock: 5,  maxStock: 40,  unit: 'frasco',   categoryId: 1, category: 'Aceites y Condimentos', isActive: true, sucursalId: 'branch-001' }),
    // ── Sucursal Miraflores (branch-002) ─────────────────────────────────
    new Product({ id: 13, name: 'Aceite de Oliva Extra Virgen', description: 'Aceite importado para cocina y ensaladas',     sku: 'INV-ACE-002', price: 45.00, cost: 32.00, stock: 10,  minStock: 5,  maxStock: 50,  unit: 'botella',  categoryId: 1, category: 'Aceites y Condimentos', isActive: true, sucursalId: 'branch-002' }),
    new Product({ id: 14, name: 'Lomo Fino',                    description: 'Lomo fino de res para lomo saltado',            sku: 'INV-LOM-002', price: 42.00, cost: 30.00, stock: 6,   minStock: 5,  maxStock: 25,  unit: 'kg',       categoryId: 3, category: 'Carnes y Pescados',      isActive: true, sucursalId: 'branch-002' }),
    new Product({ id: 15, name: 'Maíz Morado',                  description: 'Maíz morado seco para chicha morada',          sku: 'INV-MAI-002', price: 5.00,  cost: 2.50,  stock: 25,  minStock: 8,  maxStock: 60,  unit: 'kg',       categoryId: 5, category: 'Frutas y Verduras',      isActive: true, sucursalId: 'branch-002' }),
    new Product({ id: 16, name: 'Papa Amarilla',                description: 'Papa amarilla para causa y guarniciones',       sku: 'INV-PAP-002', price: 4.00,  cost: 2.00,  stock: 2,   minStock: 10, maxStock: 50,  unit: 'kg',       categoryId: 5, category: 'Frutas y Verduras',      isActive: true, sucursalId: 'branch-002' }),
];

export const MOCK_STOCK_MOVEMENTS = [
    // ── Sede Central (branch-001) — últimos 7 días ────────────────────────
    new StockMovement({ id: 1,  productId: 1,  productName: 'Aceite de Oliva Extra Virgen', productSku: 'INV-ACE-001', type: MOVEMENT_TYPE.PURCHASE,   direction: MOVEMENT_DIRECTION.IN,  quantity: 12, previousStock: 12, newStock: 24, reason: 'Compra a proveedor', notes: 'Factura #F001-2480',            userName: 'Carlos López',  sucursalId: 'branch-001', createdAt: '2026-04-01T09:15:00' }),
    new StockMovement({ id: 2,  productId: 4,  productName: 'Pechuga de Pollo',             productSku: 'INV-POL-001', type: MOVEMENT_TYPE.USAGE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 5,  previousStock: 8,  newStock: 3,  reason: 'Uso en cocina',      notes: 'Turno almuerzo',                   userName: 'María García',  sucursalId: 'branch-001', createdAt: '2026-04-01T14:30:00' }),
    new StockMovement({ id: 3,  productId: 8,  productName: 'Limones Frescos',              productSku: 'INV-LIM-001', type: MOVEMENT_TYPE.WASTE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 3,  previousStock: 3,  newStock: 0,  reason: 'Merma / vencido',    notes: 'Limones malogrados',                userName: 'Carlos López',  sucursalId: 'branch-001', createdAt: '2026-04-01T08:00:00' }),
    new StockMovement({ id: 4,  productId: 3,  productName: 'Filete de Salmón',             productSku: 'INV-SAL-001', type: MOVEMENT_TYPE.USAGE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 4,  previousStock: 16, newStock: 12, reason: 'Uso en cocina',      notes: 'Preparación ceviche especial',      userName: 'María García',  sucursalId: 'branch-001', createdAt: '2026-03-31T13:00:00' }),
    new StockMovement({ id: 5,  productId: 2,  productName: 'Arroz Extra Graneado',         productSku: 'INV-ARR-001', type: MOVEMENT_TYPE.PURCHASE,   direction: MOVEMENT_DIRECTION.IN,  quantity: 50, previousStock: 30, newStock: 80, reason: 'Compra a proveedor', notes: 'Pedido semanal',                    userName: 'Carlos López',  sucursalId: 'branch-001', createdAt: '2026-03-31T10:00:00' }),
    new StockMovement({ id: 6,  productId: 6,  productName: 'Crema de Leche',               productSku: 'INV-CRE-001', type: MOVEMENT_TYPE.USAGE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 3,  previousStock: 18, newStock: 15, reason: 'Uso en cocina',      notes: 'Salsas del día',                    userName: 'María García',  sucursalId: 'branch-001', createdAt: '2026-03-30T15:45:00' }),
    new StockMovement({ id: 7,  productId: 9,  productName: 'Cebolla Roja',                 productSku: 'INV-CEB-001', type: MOVEMENT_TYPE.ADJUSTMENT, direction: MOVEMENT_DIRECTION.IN,  quantity: 5,  previousStock: 40, newStock: 45, reason: 'Ajuste por conteo',  notes: 'Conteo físico semanal',             userName: 'Carlos López',  sucursalId: 'branch-001', createdAt: '2026-03-30T08:30:00' }),
    new StockMovement({ id: 8,  productId: 10, productName: 'Café Molido Premium',           productSku: 'INV-CAF-001', type: MOVEMENT_TYPE.USAGE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 2,  previousStock: 12, newStock: 10, reason: 'Uso en cocina',      notes: 'Consumo barra de café',             userName: 'Ana Torres',    sucursalId: 'branch-001', createdAt: '2026-03-29T11:00:00' }),
    new StockMovement({ id: 9,  productId: 5,  productName: 'Queso Parmesano',              productSku: 'INV-QUE-001', type: MOVEMENT_TYPE.PURCHASE,   direction: MOVEMENT_DIRECTION.IN,  quantity: 5,  previousStock: 3,  newStock: 8,  reason: 'Compra a proveedor', notes: 'Proveedor LactoPeru',                userName: 'Carlos López',  sucursalId: 'branch-001', createdAt: '2026-03-28T09:00:00' }),
    new StockMovement({ id: 10, productId: 12, productName: 'Ají Amarillo en Pasta',        productSku: 'INV-AJI-001', type: MOVEMENT_TYPE.USAGE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 2,  previousStock: 20, newStock: 18, reason: 'Uso en cocina',      notes: 'Preparación de ají de gallina',     userName: 'María García',  sucursalId: 'branch-001', createdAt: '2026-03-28T14:20:00' }),    new StockMovement({ id: 13, productId: 7,  productName: 'Fettuccine Pasta',             productSku: 'INV-PAS-001', type: MOVEMENT_TYPE.USAGE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 4,  previousStock: 34, newStock: 30, reason: 'Uso en cocina',      notes: 'Preparación de pastas del día',     userName: 'Ana Torres',    sucursalId: 'branch-001', createdAt: '2026-04-01T12:10:00' }),
    new StockMovement({ id: 14, productId: 11, productName: 'Servilletas Decoradas',         productSku: 'INV-SER-001', type: MOVEMENT_TYPE.PURCHASE,   direction: MOVEMENT_DIRECTION.IN,  quantity: 100,previousStock: 50, newStock: 150,reason: 'Compra a proveedor', notes: 'Reposición mensual',                userName: 'Carlos López',  sucursalId: 'branch-001', createdAt: '2026-03-29T08:45:00' }),
    new StockMovement({ id: 15, productId: 4,  productName: 'Pechuga de Pollo',             productSku: 'INV-POL-001', type: MOVEMENT_TYPE.WASTE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 1,  previousStock: 4,  newStock: 3,  reason: 'Merma / vencido',    notes: 'Porción con mal aspecto',           userName: 'Pedro Ramos',   sucursalId: 'branch-001', createdAt: '2026-03-30T17:00:00' }),
    new StockMovement({ id: 16, productId: 6,  productName: 'Crema de Leche',               productSku: 'INV-CRE-001', type: MOVEMENT_TYPE.PURCHASE,   direction: MOVEMENT_DIRECTION.IN,  quantity: 10, previousStock: 5,  newStock: 15, reason: 'Compra a proveedor', notes: 'Pedido urgente a GloriaShop',       userName: 'Carlos López',  sucursalId: 'branch-001', createdAt: '2026-03-29T16:30:00' }),
    new StockMovement({ id: 17, productId: 9,  productName: 'Cebolla Roja',                 productSku: 'INV-CEB-001', type: MOVEMENT_TYPE.USAGE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 8,  previousStock: 53, newStock: 45, reason: 'Uso en cocina',      notes: 'Ceviche del fin de semana',         userName: 'María García',  sucursalId: 'branch-001', createdAt: '2026-03-30T13:15:00' }),    // ── Sucursal Miraflores (branch-002) ─────────────────────────────────
    new StockMovement({ id: 11, productId: 14, productName: 'Lomo Fino',                    productSku: 'INV-LOM-002', type: MOVEMENT_TYPE.USAGE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 4,  previousStock: 10, newStock: 6,  reason: 'Uso en cocina',      notes: 'Turno almuerzo lomo saltado',       userName: 'Pedro Ramos',   sucursalId: 'branch-002', createdAt: '2026-04-01T13:30:00' }),
    new StockMovement({ id: 12, productId: 16, productName: 'Papa Amarilla',                productSku: 'INV-PAP-002', type: MOVEMENT_TYPE.WASTE,      direction: MOVEMENT_DIRECTION.OUT, quantity: 3,  previousStock: 5,  newStock: 2,  reason: 'Merma / vencido',    notes: 'Papas en mal estado',               userName: 'Pedro Ramos',   sucursalId: 'branch-002', createdAt: '2026-03-31T08:15:00' }),
];
