/**
 * Cash Register Infrastructure — Mock Data
 *
 * Simula sesiones de caja (turnos) y movimientos de efectivo
 * filtrables por sucursal (gs_branch_id).
 */
import { CashRegisterSession, SESSION_STATUS } from '../domain/models/cash-register-session.entity.js';
import { CashMovement } from '../domain/models/cash-movement.entity.js';

// ── Helpers ────────────────────────────────────────────────────────────────
function _daysAgo(n, h = 8, m = 0) {
    const d = new Date();
    d.setDate(d.getDate() - n);
    d.setHours(h, m, 0, 0);
    return d.toISOString();
}

// ── Sessions (turnos) ──────────────────────────────────────────────────────
export const MOCK_SESSIONS = [
    // Sede Central — turno abierto hoy
    new CashRegisterSession({
        id:            'session-001',
        openedAt:      _daysAgo(0, 8, 0),
        closedAt:      null,
        openedBy:      'Ana Quispe Vargas',
        closedBy:      null,
        initialAmount: 200.00,
        finalAmount:   null,
        status:        SESSION_STATUS.OPEN,
        sucursalId:    'branch-001',
        shiftName:     'Mañana',
        notes:         'Turno matutino',
    }),
    // Sede Central — turno cerrado ayer (con faltante)
    new CashRegisterSession({
        id:            'session-002',
        openedAt:      _daysAgo(1, 8, 0),
        closedAt:      _daysAgo(1, 22, 30),
        openedBy:      'Ana Quispe Vargas',
        closedBy:      'Carlos Mendoza Rivera',
        initialAmount: 200.00,
        finalAmount:   1845.50,
        status:        SESSION_STATUS.CLOSED,
        sucursalId:    'branch-001',
        shiftName:     'Completo',
        totalSales:    18,
        totalRevenue:  1690.50,
        cashRevenue:   1250.00,
        digitalRevenue: 440.50,
        expectedCash:  1405.00,
        countedAmount: 1385.50,
        difference:    -19.50,
        notes:         'Turno completo día anterior — faltante de S/19.50',
    }),
    // Sede Central — turno cerrado hace 2 días (cuadrado)
    new CashRegisterSession({
        id:            'session-003',
        openedAt:      _daysAgo(2, 8, 0),
        closedAt:      _daysAgo(2, 22, 0),
        openedBy:      'Ana Quispe Vargas',
        closedBy:      'Ana Quispe Vargas',
        initialAmount: 150.00,
        finalAmount:   1320.00,
        status:        SESSION_STATUS.CLOSED,
        sucursalId:    'branch-001',
        shiftName:     'Completo',
        totalSales:    14,
        totalRevenue:  1320.00,
        cashRevenue:   1020.00,
        digitalRevenue: 300.00,
        expectedCash:  1170.00,
        countedAmount: 1170.00,
        difference:    0,
        notes:         '',
    }),
    // Miraflores — sin turno abierto (con sobrante)
    new CashRegisterSession({
        id:            'session-004',
        openedAt:      _daysAgo(1, 9, 0),
        closedAt:      _daysAgo(1, 21, 0),
        openedBy:      'Luis Paredes Soto',
        closedBy:      'Luis Paredes Soto',
        initialAmount: 300.00,
        finalAmount:   2150.00,
        status:        SESSION_STATUS.CLOSED,
        sucursalId:    'branch-002',
        shiftName:     'Completo',
        totalSales:    22,
        totalRevenue:  2150.00,
        cashRevenue:   1880.00,
        digitalRevenue: 270.00,
        expectedCash:  2150.00,
        countedAmount: 2155.00,
        difference:    5.00,
        notes:         'Turno único Miraflores — sobrante S/5',
    }),
];

// ── Movements ──────────────────────────────────────────────────────────────
export const MOCK_MOVEMENTS = [
    // Movimientos del turno abierto hoy (session-001)
    new CashMovement({
        id:          'mov-001',
        type:        'income',
        amount:      200.00,
        description: 'Fondo de caja inicial',
        sessionId:   'session-001',
        registerId:  'session-001',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'apertura',
        createdAt:   _daysAgo(0, 8, 0),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-002',
        type:        'income',
        amount:      85.50,
        description: 'Pago Mesa 3 — Efectivo',
        sessionId:   'session-001',
        registerId:  'session-001',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'venta',
        paymentId:   'pay-101',
        createdAt:   _daysAgo(0, 9, 15),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-002b',
        type:        'income',
        amount:      62.00,
        description: 'Pago Mesa 5 — Yape',
        sessionId:   'session-001',
        registerId:  'session-001',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'venta_digital',
        paymentId:   'pay-102',
        createdAt:   _daysAgo(0, 9, 45),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-003',
        type:        'income',
        amount:      142.00,
        description: 'Pago Mesa 7 — Efectivo',
        sessionId:   'session-001',
        registerId:  'session-001',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'venta',
        paymentId:   'pay-103',
        createdAt:   _daysAgo(0, 10, 30),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-004',
        type:        'expense',
        amount:      25.00,
        description: 'Compra de limones — proveedor rápido',
        sessionId:   'session-001',
        registerId:  'session-001',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'compra',
        createdAt:   _daysAgo(0, 11, 0),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-005',
        type:        'income',
        amount:      67.00,
        description: 'Pago Mesa 1 — Efectivo',
        sessionId:   'session-001',
        registerId:  'session-001',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'venta',
        paymentId:   'pay-104',
        createdAt:   _daysAgo(0, 12, 45),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-005b',
        type:        'income',
        amount:      48.50,
        description: 'Pago Mesa 2 — Tarjeta',
        sessionId:   'session-001',
        registerId:  'session-001',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'venta_digital',
        paymentId:   'pay-105',
        createdAt:   _daysAgo(0, 13, 0),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-006',
        type:        'expense',
        amount:      15.00,
        description: 'Retiro personal — autorizado',
        sessionId:   'session-001',
        registerId:  'session-001',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'retiro',
        createdAt:   _daysAgo(0, 13, 20),
        sucursalId:  'branch-001',
    }),

    // Movimientos del turno cerrado ayer (session-002)
    new CashMovement({
        id:          'mov-007',
        type:        'income',
        amount:      200.00,
        description: 'Fondo de caja inicial',
        sessionId:   'session-002',
        registerId:  'session-002',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'apertura',
        createdAt:   _daysAgo(1, 8, 0),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-008',
        type:        'income',
        amount:      1250.00,
        description: 'Ventas en efectivo acumuladas',
        sessionId:   'session-002',
        registerId:  'session-002',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'venta',
        createdAt:   _daysAgo(1, 21, 0),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-008b',
        type:        'income',
        amount:      440.50,
        description: 'Ventas digitales acumuladas (Yape/Tarjeta)',
        sessionId:   'session-002',
        registerId:  'session-002',
        userId:      'user-004',
        userName:    'Ana Quispe Vargas',
        category:    'venta_digital',
        createdAt:   _daysAgo(1, 21, 0),
        sucursalId:  'branch-001',
    }),
    new CashMovement({
        id:          'mov-009',
        type:        'expense',
        amount:      45.00,
        description: 'Insumos de limpieza',
        sessionId:   'session-002',
        registerId:  'session-002',
        userId:      'user-001',
        userName:    'Carlos Mendoza Rivera',
        category:    'compra',
        createdAt:   _daysAgo(1, 15, 0),
        sucursalId:  'branch-001',
    }),

    // Movimientos Miraflores (session-004)
    new CashMovement({
        id:          'mov-010',
        type:        'income',
        amount:      300.00,
        description: 'Fondo de caja inicial',
        sessionId:   'session-004',
        registerId:  'session-004',
        userId:      'user-005',
        userName:    'Luis Paredes Soto',
        category:    'apertura',
        createdAt:   _daysAgo(1, 9, 0),
        sucursalId:  'branch-002',
    }),
    new CashMovement({
        id:          'mov-011',
        type:        'income',
        amount:      1880.00,
        description: 'Ventas en efectivo acumuladas',
        sessionId:   'session-004',
        registerId:  'session-004',
        userId:      'user-005',
        userName:    'Luis Paredes Soto',
        category:    'venta',
        createdAt:   _daysAgo(1, 20, 30),
        sucursalId:  'branch-002',
    }),
    new CashMovement({
        id:          'mov-011b',
        type:        'income',
        amount:      270.00,
        description: 'Ventas digitales acumuladas',
        sessionId:   'session-004',
        registerId:  'session-004',
        userId:      'user-005',
        userName:    'Luis Paredes Soto',
        category:    'venta_digital',
        createdAt:   _daysAgo(1, 20, 30),
        sucursalId:  'branch-002',
    }),
    new CashMovement({
        id:          'mov-012',
        type:        'expense',
        amount:      30.00,
        description: 'Delivery urgente proveedor',
        sessionId:   'session-004',
        registerId:  'session-004',
        userId:      'user-005',
        userName:    'Luis Paredes Soto',
        category:    'compra',
        createdAt:   _daysAgo(1, 14, 0),
        sucursalId:  'branch-002',
    }),
];
