import { Payment, PAYMENT_STATUS, PAYMENT_METHOD, RECEIPT_TYPE } from '../domain/models/payment.entity.js';

const today = new Date();
const t = (h, m) => new Date(today.getFullYear(), today.getMonth(), today.getDate(), h, m);

export const MOCK_PAYMENTS = [
    // ── Sede Central (branch-001) ────────────────────────────────────────
    new Payment({ id: 1001, saleId: 301, tableNumber: 5,  zoneName: 'Terraza',  items: [{ name: 'Lomo Saltado', qty: 2, subtotal: 52.00 }, { name: 'Inca Kola 500ml', qty: 2, subtotal: 12.00 }], subtotal: 54.24, tax: 9.76, discount: 0, total: 64.00,  method: PAYMENT_METHOD.CASH, amountReceived: 100, change: 36.00, receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '45678912', nombre: 'Carlos Mendes'      }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(9,  15), sucursalId: 'branch-001' }),
    new Payment({ id: 1002, saleId: 302, tableNumber: 2,  zoneName: 'Interior', items: [{ name: 'Ceviche Mixto', qty: 1, subtotal: 45.00 }, { name: 'Chicha Morada', qty: 2, subtotal: 10.00 }], subtotal: 46.61, tax: 8.39, discount: 5, total: 50.00,  method: PAYMENT_METHOD.YAPE,  amountReceived: 50,  change: 0,     receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: t(10, 30), sucursalId: 'branch-001' }),
    new Payment({ id: 1003, saleId: 303, tableNumber: 8,  zoneName: 'Jardín',   items: [{ name: 'Arroz con Leche', qty: 3, subtotal: 21.00 }, { name: 'Café Americano', qty: 3, subtotal: 18.00 }], subtotal: 33.05, tax: 5.95, discount: 0, total: 39.00,  method: PAYMENT_METHOD.CARD,  amountReceived: 39,  change: 0,     receiptType: RECEIPT_TYPE.FACTURA, receiptData: { ruc: '20512345678', razonSocial: 'Eventos SAC', direccion: 'Av. Lima 230' }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(11, 45), sucursalId: 'branch-001' }),
    new Payment({ id: 1004, saleId: 304, tableNumber: 1,  zoneName: 'Interior', items: [{ name: 'Pizza Napolitana', qty: 1, subtotal: 38.00 }],                                                   subtotal: 32.20, tax: 5.80, discount: 0, total: 38.00,  method: PAYMENT_METHOD.PLIN,  amountReceived: 38,  change: 0,     receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '12345678', nombre: 'María Torres'       }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(12, 10), sucursalId: 'branch-001' }),
    new Payment({ id: 1005, saleId: 305, tableNumber: 3,  zoneName: 'Terraza',  items: [{ name: 'Tacu Tacu', qty: 2, subtotal: 60.00 }, { name: 'Jugo Natural', qty: 2, subtotal: 16.00 }],      subtotal: 64.41, tax: 11.59, discount: 0, total: 76.00, method: PAYMENT_METHOD.CASH, amountReceived: 100, change: 24.00, receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: t(13, 5),  sucursalId: 'branch-001' }),
    // ── Sucursal Miraflores (branch-002) ─────────────────────────────────
    new Payment({ id: 1006, saleId: 306, tableNumber: 6,  zoneName: 'Jardín',   items: [{ name: 'Causa Rellena', qty: 2, subtotal: 30.00 }, { name: 'Agua San Luis', qty: 2, subtotal: 8.00 }],  subtotal: 32.20, tax: 5.80, discount: 0, total: 38.00,  method: PAYMENT_METHOD.YAPE,  amountReceived: 38,  change: 0,     receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '87654321', nombre: 'José Quispe'        }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(14, 20), sucursalId: 'branch-002' }),
    new Payment({ id: 1007, saleId: 307, tableNumber: 4,  zoneName: 'Interior', items: [{ name: 'Sopa Criolla', qty: 1, subtotal: 22.00 }, { name: 'Gaseosa 1L', qty: 1, subtotal: 8.00 }],     subtotal: 25.42, tax: 4.58, discount: 0, total: 30.00,  method: PAYMENT_METHOD.CARD,  amountReceived: 30,  change: 0,     receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: t(15, 0),  sucursalId: 'branch-002' }),
    new Payment({ id: 1008, saleId: 308, tableNumber: 7,  zoneName: 'Terraza',  items: [{ name: 'Pollo a la Brasa', qty: 1, subtotal: 55.00 }, { name: 'Papas Fritas', qty: 2, subtotal: 16.00 }, { name: 'Inca Kola 1.5L', qty: 1, subtotal: 9.00 }], subtotal: 67.80, tax: 12.20, discount: 0, total: 80.00, method: PAYMENT_METHOD.CASH, amountReceived: 100, change: 20.00, receiptType: RECEIPT_TYPE.FACTURA, receiptData: { ruc: '20601234567', razonSocial: 'Tech Corp EIRL', direccion: 'Jr. Puno 456' }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(16, 35), sucursalId: 'branch-002' }),
];
