import { Payment, PAYMENT_STATUS, PAYMENT_METHOD, RECEIPT_TYPE } from '../domain/models/payment.entity.js';

const today = new Date();
const t = (h, m) => new Date(today.getFullYear(), today.getMonth(), today.getDate(), h, m);
const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1);
const y = (h, m) => new Date(yesterday.getFullYear(), yesterday.getMonth(), yesterday.getDate(), h, m);
const twoDaysAgo = new Date(today); twoDaysAgo.setDate(today.getDate() - 2);
const d2 = (h, m) => new Date(twoDaysAgo.getFullYear(), twoDaysAgo.getMonth(), twoDaysAgo.getDate(), h, m);

export const MOCK_PAYMENTS = [
    // ── Sede Central (branch-001) — Zonas: Salón Principal, Terraza, Privado ──
    new Payment({ id: 1001, saleId: 301, tableNumber: 5,  zoneName: 'Salón Principal',  items: [{ name: 'Lomo Saltado', qty: 2, subtotal: 52.00 }, { name: 'Inca Kola 500ml', qty: 2, subtotal: 12.00 }], subtotal: 54.24, tax: 9.76, discount: 0, total: 64.00,  method: PAYMENT_METHOD.CASH, amountReceived: 100, change: 36.00, receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '45678912', nombre: 'Carlos Mendes'      }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(9,  15), sucursalId: 'branch-001' }),
    new Payment({ id: 1002, saleId: 302, tableNumber: 2,  zoneName: 'Salón Principal', items: [{ name: 'Ceviche Mixto', qty: 1, subtotal: 45.00 }, { name: 'Chicha Morada', qty: 2, subtotal: 10.00 }], subtotal: 46.61, tax: 8.39, discount: 5, total: 50.00,  method: PAYMENT_METHOD.YAPE,  amountReceived: 50,  change: 0,     receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: t(10, 30), sucursalId: 'branch-001' }),
    new Payment({ id: 1003, saleId: 303, tableNumber: 8,  zoneName: 'Terraza',   items: [{ name: 'Arroz con Leche', qty: 3, subtotal: 21.00 }, { name: 'Café Americano', qty: 3, subtotal: 18.00 }], subtotal: 33.05, tax: 5.95, discount: 0, total: 39.00,  method: PAYMENT_METHOD.CARD,  amountReceived: 39,  change: 0,     receiptType: RECEIPT_TYPE.FACTURA, receiptData: { ruc: '20512345678', razonSocial: 'Eventos SAC', direccion: 'Av. Lima 230' }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(11, 45), sucursalId: 'branch-001' }),
    new Payment({ id: 1004, saleId: 304, tableNumber: 1,  zoneName: 'Salón Principal', items: [{ name: 'Pizza Napolitana', qty: 1, subtotal: 38.00 }],                                                   subtotal: 32.20, tax: 5.80, discount: 0, total: 38.00,  method: PAYMENT_METHOD.PLIN,  amountReceived: 38,  change: 0,     receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '12345678', nombre: 'María Torres'       }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(12, 10), sucursalId: 'branch-001' }),
    new Payment({ id: 1005, saleId: 305, tableNumber: 3,  zoneName: 'Salón Principal',  items: [{ name: 'Tacu Tacu', qty: 2, subtotal: 60.00 }, { name: 'Jugo Natural', qty: 2, subtotal: 16.00 }],      subtotal: 64.41, tax: 11.59, discount: 0, total: 76.00, method: PAYMENT_METHOD.CASH, amountReceived: 100, change: 24.00, receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: t(13, 5),  sucursalId: 'branch-001' }),
    // ── Sucursal Miraflores (branch-002) — Zonas: Salón Miraflores, Barra ─────
    new Payment({ id: 1006, saleId: 306, tableNumber: 3,  zoneName: 'Salón Miraflores',   items: [{ name: 'Causa Rellena', qty: 2, subtotal: 30.00 }, { name: 'Agua San Luis', qty: 2, subtotal: 8.00 }],  subtotal: 32.20, tax: 5.80, discount: 0, total: 38.00,  method: PAYMENT_METHOD.YAPE,  amountReceived: 38,  change: 0,     receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '87654321', nombre: 'José Quispe'        }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(14, 20), sucursalId: 'branch-002' }),
    new Payment({ id: 1007, saleId: 307, tableNumber: 4,  zoneName: 'Barra', items: [{ name: 'Sopa Criolla', qty: 1, subtotal: 22.00 }, { name: 'Gaseosa 1L', qty: 1, subtotal: 8.00 }],     subtotal: 25.42, tax: 4.58, discount: 0, total: 30.00,  method: PAYMENT_METHOD.CARD,  amountReceived: 30,  change: 0,     receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: t(15, 0),  sucursalId: 'branch-002' }),
    new Payment({ id: 1008, saleId: 308, tableNumber: 5,  zoneName: 'Barra',  items: [{ name: 'Pollo a la Brasa', qty: 1, subtotal: 55.00 }, { name: 'Papas Fritas', qty: 2, subtotal: 16.00 }, { name: 'Inca Kola 1.5L', qty: 1, subtotal: 9.00 }], subtotal: 67.80, tax: 12.20, discount: 0, total: 80.00, method: PAYMENT_METHOD.CASH, amountReceived: 100, change: 20.00, receiptType: RECEIPT_TYPE.FACTURA, receiptData: { ruc: '20601234567', razonSocial: 'Tech Corp EIRL', direccion: 'Jr. Puno 456' }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(16, 35), sucursalId: 'branch-002' }),
    // ── División de cuenta (splitGroupId compartido) ─────────────────────
    new Payment({ id: 1009, saleId: 309, tableNumber: 10, zoneName: 'Terraza', items: [{ name: 'Lomo Saltado', qty: 1, subtotal: 26.00 }], subtotal: 22.03, tax: 3.97, discount: 0, total: 26.00, method: PAYMENT_METHOD.CASH, amountReceived: 30, change: 4.00, receiptType: RECEIPT_TYPE.NOTA, receiptData: {}, status: PAYMENT_STATUS.COMPLETED, processedAt: t(17, 0), sucursalId: 'branch-001', note: 'División: Persona 1', splitGroupId: 'split-group-001', isSplit: true, splitIndex: 0, splitCount: 3 }),
    new Payment({ id: 1010, saleId: 309, tableNumber: 10, zoneName: 'Terraza', items: [{ name: 'Ceviche Mixto', qty: 1, subtotal: 45.00 }], subtotal: 38.14, tax: 6.86, discount: 0, total: 45.00, method: PAYMENT_METHOD.YAPE, amountReceived: 45, change: 0, receiptType: RECEIPT_TYPE.NOTA, receiptData: {}, status: PAYMENT_STATUS.COMPLETED, processedAt: t(17, 0), sucursalId: 'branch-001', note: 'División: Persona 2', splitGroupId: 'split-group-001', isSplit: true, splitIndex: 1, splitCount: 3 }),
    new Payment({ id: 1011, saleId: 309, tableNumber: 10, zoneName: 'Terraza', items: [{ name: 'Chicha Morada', qty: 2, subtotal: 10.00 }, { name: 'Arroz con Leche', qty: 1, subtotal: 7.00 }], subtotal: 14.41, tax: 2.59, discount: 0, total: 17.00, method: PAYMENT_METHOD.CARD, amountReceived: 17, change: 0, receiptType: RECEIPT_TYPE.NOTA, receiptData: {}, status: PAYMENT_STATUS.COMPLETED, processedAt: t(17, 0), sucursalId: 'branch-001', note: 'División: Persona 3', splitGroupId: 'split-group-001', isSplit: true, splitIndex: 2, splitCount: 3 }),
    // ── Más pagos de hoy (para llenar paginación) ────────────────────────
    new Payment({ id: 1012, saleId: 310, tableNumber: 9,  zoneName: 'Terraza',  items: [{ name: 'Ají de Gallina', qty: 2, subtotal: 36.00 }, { name: 'Chicha Morada', qty: 2, subtotal: 10.00 }], subtotal: 38.98, tax: 7.02, discount: 0, total: 46.00,  method: PAYMENT_METHOD.CASH, amountReceived: 50, change: 4.00, receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '71234567', nombre: 'Ana Gutiérrez' }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(17, 30), sucursalId: 'branch-001' }),
    new Payment({ id: 1013, saleId: 311, tableNumber: 3,  zoneName: 'Salón Principal', items: [{ name: 'Seco de Res', qty: 1, subtotal: 28.00 }, { name: 'Jugo de Maracuyá', qty: 1, subtotal: 8.00 }], subtotal: 30.51, tax: 5.49, discount: 0, total: 36.00,  method: PAYMENT_METHOD.YAPE, amountReceived: 36,  change: 0,    receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: t(18, 15), sucursalId: 'branch-001' }),
    new Payment({ id: 1014, saleId: 312, tableNumber: 2,  zoneName: 'Salón Miraflores',   items: [{ name: 'Anticuchos', qty: 3, subtotal: 36.00 }],                                                        subtotal: 30.51, tax: 5.49, discount: 0, total: 36.00,  method: PAYMENT_METHOD.PLIN, amountReceived: 36,  change: 0,    receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '43218765', nombre: 'Luis Paredes' },    status: PAYMENT_STATUS.COMPLETED, processedAt: t(18, 45), sucursalId: 'branch-002' }),
    new Payment({ id: 1015, saleId: 313, tableNumber: 4,  zoneName: 'Salón Principal', items: [{ name: 'Rocoto Relleno', qty: 2, subtotal: 42.00 }, { name: 'Agua San Luis', qty: 2, subtotal: 8.00 }], subtotal: 42.37, tax: 7.63, discount: 0, total: 50.00,  method: PAYMENT_METHOD.CARD, amountReceived: 50,  change: 0,    receiptType: RECEIPT_TYPE.FACTURA, receiptData: { ruc: '20789012345', razonSocial: 'Distribuidora Norte SAC', direccion: 'Av. Arequipa 1500' }, status: PAYMENT_STATUS.COMPLETED, processedAt: t(19, 0), sucursalId: 'branch-001' }),
    // ── Pagos de ayer ────────────────────────────────────────────────────
    new Payment({ id: 1016, saleId: 314, tableNumber: 7,  zoneName: 'Terraza',  items: [{ name: 'Tacu Tacu', qty: 1, subtotal: 30.00 }, { name: 'Inca Kola 500ml', qty: 1, subtotal: 6.00 }],   subtotal: 30.51, tax: 5.49, discount: 0, total: 36.00,  method: PAYMENT_METHOD.CASH, amountReceived: 50,  change: 14.00, receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: y(10, 0),  sucursalId: 'branch-001' }),
    new Payment({ id: 1017, saleId: 315, tableNumber: 5,  zoneName: 'Salón Principal', items: [{ name: 'Ceviche Mixto', qty: 2, subtotal: 90.00 }],                                                     subtotal: 76.27, tax: 13.73, discount: 0, total: 90.00, method: PAYMENT_METHOD.YAPE, amountReceived: 90,  change: 0,    receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '56789012', nombre: 'Pedro Ramos' },     status: PAYMENT_STATUS.COMPLETED, processedAt: y(12, 30), sucursalId: 'branch-001' }),
    new Payment({ id: 1018, saleId: 316, tableNumber: 1,  zoneName: 'Salón Miraflores',   items: [{ name: 'Papa a la Huancaína', qty: 3, subtotal: 27.00 }, { name: 'Café Americano', qty: 3, subtotal: 18.00 }], subtotal: 38.14, tax: 6.86, discount: 0, total: 45.00, method: PAYMENT_METHOD.CARD, amountReceived: 45, change: 0, receiptType: RECEIPT_TYPE.NOTA, receiptData: {}, status: PAYMENT_STATUS.COMPLETED, processedAt: y(14, 15), sucursalId: 'branch-002' }),
    new Payment({ id: 1019, saleId: 317, tableNumber: 1,  zoneName: 'Salón Principal', items: [{ name: 'Lomo Saltado', qty: 1, subtotal: 26.00 }, { name: 'Gaseosa 1L', qty: 1, subtotal: 8.00 }],     subtotal: 28.81, tax: 5.19, discount: 0, total: 34.00,  method: PAYMENT_METHOD.PLIN, amountReceived: 34,  change: 0,    receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '34567890', nombre: 'Sandra Vega' },     status: PAYMENT_STATUS.COMPLETED, processedAt: y(16, 0),  sucursalId: 'branch-001' }),
    new Payment({ id: 1020, saleId: 318, tableNumber: 5,  zoneName: 'Barra',  items: [{ name: 'Pollo a la Brasa', qty: 1, subtotal: 55.00 }, { name: 'Ensalada', qty: 1, subtotal: 12.00 }],   subtotal: 56.78, tax: 10.22, discount: 0, total: 67.00, method: PAYMENT_METHOD.CASH, amountReceived: 70,  change: 3.00, receiptType: RECEIPT_TYPE.FACTURA, receiptData: { ruc: '20345678901', razonSocial: 'Grupo Pacífico EIRL', direccion: 'Calle Los Pinos 789' }, status: PAYMENT_STATUS.COMPLETED, processedAt: y(18, 20), sucursalId: 'branch-002' }),
    // ── Pagos de hace 2 días ────────────────────────────────────────────
    new Payment({ id: 1021, saleId: 319, tableNumber: 3,  zoneName: 'Salón Principal', items: [{ name: 'Arroz Chaufa', qty: 2, subtotal: 36.00 }],                                                      subtotal: 30.51, tax: 5.49, discount: 0, total: 36.00,  method: PAYMENT_METHOD.YAPE, amountReceived: 36,  change: 0,    receiptType: RECEIPT_TYPE.NOTA,    receiptData: {},                                             status: PAYMENT_STATUS.COMPLETED, processedAt: d2(11, 0), sucursalId: 'branch-001' }),
    new Payment({ id: 1022, saleId: 320, tableNumber: 9,  zoneName: 'Terraza',   items: [{ name: 'Pizza Napolitana', qty: 1, subtotal: 38.00 }, { name: 'Limonada', qty: 2, subtotal: 14.00 }],   subtotal: 44.07, tax: 7.93, discount: 0, total: 52.00,  method: PAYMENT_METHOD.CARD, amountReceived: 52,  change: 0,    receiptType: RECEIPT_TYPE.BOLETA,  receiptData: { dni: '23456789', nombre: 'Roberto Flores' },  status: PAYMENT_STATUS.COMPLETED, processedAt: d2(13, 45), sucursalId: 'branch-001' }),
    new Payment({ id: 1023, saleId: 321, tableNumber: 4,  zoneName: 'Barra',  items: [{ name: 'Sopa Criolla', qty: 2, subtotal: 44.00 }, { name: 'Pan con Chicharrón', qty: 2, subtotal: 20.00 }], subtotal: 54.24, tax: 9.76, discount: 0, total: 64.00, method: PAYMENT_METHOD.CASH, amountReceived: 100, change: 36.00, receiptType: RECEIPT_TYPE.NOTA, receiptData: {}, status: PAYMENT_STATUS.COMPLETED, processedAt: d2(15, 30), sucursalId: 'branch-002' }),
];
